### ISSUE TITLE
Can't start the plugin

### ISSUE THREAD

**Issue by viq** [reikoNeko/icinga2bot#1]
After installing and configuring, both on debian 8 and ubuntu 16.04 I see:
```
!plugin activate icinga2bot
Error activating plugin: icinga2bot failed to start : 'Icinga2bot' object has no attribute 'thread'
```

**Comment by reikoNeko** [comment]
My development and testing is done primarily in Centos 6. Can you give me a little more information about your Python environment and what version of Errbot you're using?
You should also see any plugin startup errors in your Errbot logs. If you have them, please forward.

Sorry it took me a while to notice this; it was buried in issues of other projects I've been watching.

**Comment by viq** [comment]
Sorry for the delay in responding.
I'm trying in a pretty much default debian 8, and going through pip install described at http://errbot.io/en/latest/user_guide/setup.html#installation. This gives me following versions:
```
$ python --version ; pip freeze | grep err
Python 3.4.2
errbot==5.0.1
```
Starting errbot with your plugin present in `~/errbot-root/plugins/` looks like this:
```
$ errbot 
15:39:54 INFO     errbot.cli                Config check passed...
15:39:54 INFO     errbot.cli                Selected backend 'Text'.
15:39:54 INFO     errbot.cli                Checking for '/home/vagrant/errbot-root/data'...
15:39:54 INFO     errbot.specific_plugin_ma storage search paths {'/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/storage'}
15:39:54 INFO     errbot.specific_plugin_ma Found those plugings available:
15:39:54 INFO     errbot.specific_plugin_ma          Shelf  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/storage/shelf.py)
15:39:54 INFO     errbot.specific_plugin_ma         Memory  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/storage/memory.py)
15:39:54 INFO     errbot.bootstrap          Found Storage plugin: 'Shelf'
Description: This is the storage plugin for the traditional shelf store for errbot.
15:39:54 DEBUG    errbot.specific_plugin_ma Refilter the plugins...
15:39:54 WARNING  yapsy                     Plugin candidate '/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/storage/memory.plug'  rejected by strategy 'SpecificBackendLocator'
15:39:54 DEBUG    errbot.specific_plugin_ma Load the one remaining...
15:39:54 DEBUG    errbot.specific_plugin_ma Class to load ShelfStoragePlugin
15:39:54 DEBUG    errbot.storage            Opening storage 'repomgr'
15:39:54 DEBUG    errbot.storage.shelf      Open shelf storage /home/vagrant/errbot-root/data/repomgr.db
15:39:54 DEBUG    errbot.storage            Opening storage 'core'
15:39:54 DEBUG    errbot.storage.shelf      Open shelf storage /home/vagrant/errbot-root/data/core.db
15:39:54 INFO     errbot.specific_plugin_ma backends search paths {'/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends'}
15:39:54 INFO     errbot.specific_plugin_ma Found those plugings available:
15:39:54 INFO     errbot.specific_plugin_ma        Hipchat  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/hipchat.py)
15:39:54 INFO     errbot.specific_plugin_ma           XMPP  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/xmpp.py)
15:39:54 INFO     errbot.specific_plugin_ma           Null  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/null.py)
15:39:54 INFO     errbot.specific_plugin_ma            IRC  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/irc.py)
15:39:54 INFO     errbot.specific_plugin_ma          Slack  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/slack.py)
15:39:54 INFO     errbot.specific_plugin_ma           Test  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/test.py)
15:39:54 INFO     errbot.specific_plugin_ma        Graphic  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/graphic.py)
15:39:54 INFO     errbot.specific_plugin_ma       Telegram  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/telegram_messenger.py)
15:39:54 INFO     errbot.specific_plugin_ma           Text  (/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/text.py)
15:39:54 INFO     errbot.bootstrap          Found Backend plugin: 'Text'
                                                Description: This is the text backend for Err.
15:39:54 DEBUG    errbot.specific_plugin_ma Refilter the plugins...
15:39:54 WARNING  yapsy                     Plugin candidate '/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/hipchat.plug'  rejected by strategy 'SpecificBackendLocator'
15:39:54 WARNING  yapsy                     Plugin candidate '/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/xmpp.plug'  rejected by strategy 'SpecificBackendLocator'
15:39:54 WARNING  yapsy                     Plugin candidate '/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/null.plug'  rejected by strategy 'SpecificBackendLocator'
15:39:54 WARNING  yapsy                     Plugin candidate '/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/irc.plug'  rejected by strategy 'SpecificBackendLocator'
15:39:54 WARNING  yapsy                     Plugin candidate '/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/slack.plug'  rejected by strategy 'SpecificBackendLocator'
15:39:54 WARNING  yapsy                     Plugin candidate '/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/test.plug'  rejected by strategy 'SpecificBackendLocator'
15:39:54 WARNING  yapsy                     Plugin candidate '/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/graphic.plug'  rejected by strategy 'SpecificBackendLocator'
15:39:54 WARNING  yapsy                     Plugin candidate '/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/backends/telegram_messenger.plug'  rejected by strategy 'SpecificBackendLocator'
15:39:54 DEBUG    errbot.specific_plugin_ma Load the one remaining...
15:39:54 DEBUG    errbot.specific_plugin_ma Class to load TextBackend
15:39:54 DEBUG    errbot.core               ErrBot init.
15:39:54 DEBUG    errbot.backends.base      Backend init.
15:39:54 DEBUG    errbot.core               created a thread pool of size 10.
15:39:54 DEBUG    errbot.backends.text      Text Backend Init.
15:39:54 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.smart_strong".
15:39:54 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.smart_strong.SmartEmphasisExtension".
15:39:54 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.fenced_code".
15:39:54 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
15:39:54 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.footnotes".
15:39:54 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
15:39:54 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.attr_list".
15:39:54 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
15:39:54 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.def_list".
15:39:54 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
15:39:54 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.tables".
15:39:54 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.tables.TableExtension".
15:39:54 DEBUG    MARKDOWN                  Successfuly imported extension module "markdown.extensions.abbr".
15:39:54 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
15:39:54 DEBUG    MARKDOWN                  Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
15:39:54 DEBUG    MARKDOWN                  Successfully loaded extension "errbot.rendering.ansiext.AnsiExtension".
15:39:54 DEBUG    errbot.core               Initializing backend storage
15:39:54 DEBUG    errbot.storage            Opening storage 'text_backend'
15:39:54 DEBUG    errbot.storage.shelf      Open shelf storage /home/vagrant/errbot-root/data/text_backend.db
15:39:54 DEBUG    errbot.plugin_manager     All plugin roots:
15:39:54 DEBUG    errbot.plugin_manager     -> /home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/core_plugins
15:39:54 DEBUG    errbot.plugin_manager     Add /home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/core_plugins to sys.path
15:39:54 DEBUG    errbot.plugin_manager     -> /home/vagrant/errbot-root/plugins/icinga2bot
15:39:54 DEBUG    errbot.plugin_manager     Add /home/vagrant/errbot-root/plugins/icinga2bot to sys.path
15:39:54 DEBUG    errbot.plugin_manager     -> /home/vagrant/errbot-root/plugins/err-example
15:39:54 DEBUG    errbot.plugin_manager     Add /home/vagrant/errbot-root/plugins/err-example to sys.path
15:39:54 DEBUG    errbot.plugin_manager     /home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/core_plugins has no requirements.txt file
15:39:54 DEBUG    errbot.plugin_manager     /home/vagrant/errbot-root/plugins/icinga2bot has no requirements.txt file
15:39:54 DEBUG    errbot.plugin_manager     /home/vagrant/errbot-root/plugins/err-example has no requirements.txt file
15:39:54 DEBUG    errbot.plugins.VersionChe Logger for plugin initialized...
15:39:54 INFO     errbot                    webhooks:  Flag to bind /echo to                           echo
15:39:54 DEBUG    errbot.plugins.Webserver  Logger for plugin initialized...
15:39:54 DEBUG    errbot.plugins.CommandNot Logger for plugin initialized...
15:39:54 DEBUG    errbot.plugins.Flows      Logger for plugin initialized...
15:39:54 DEBUG    errbot.plugins.Help       Logger for plugin initialized...
15:39:54 DEBUG    errbot.plugins.Plugins    Logger for plugin initialized...
15:39:54 DEBUG    errbot.plugins.Backup     Logger for plugin initialized...
15:39:54 DEBUG    errbot.plugins.Utils      Logger for plugin initialized...
15:39:54 DEBUG    errbot.plugins.Health     Logger for plugin initialized...
15:39:54 DEBUG    errbot.plugins.ACLs       Logger for plugin initialized...
15:39:54 DEBUG    errbot.plugins.ChatRoom   Logger for plugin initialized...
/home/vagrant/errbot-root
15:39:54 INFO     icinga2bot                Connected to https://localhost:5665/v1.
15:39:54 ERROR    yapsy                     Unable to create plugin object: /home/vagrant/errbot-root/plugins/icinga2bot/icinga2bot
Traceback (most recent call last):
  File "/home/vagrant/.errbot-ve/lib/python3.4/site-packages/yapsy/PluginManager.py", line 512, in loadPlugins
    plugin_info.plugin_object = self.instanciateElement(element)
  File "/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/plugin_manager.py", line 265, in instanciateElement
    return element(self.bot, name=self._current_pluginfo.name)
TypeError: __init__() got an unexpected keyword argument 'name'
15:39:54 DEBUG    errbot.plugins.Example    Logger for plugin initialized...
15:39:54 ERROR    errbot.bootstrap          Some plugins failed to load:
  File "/home/vagrant/.errbot-ve/lib/python3.4/site-packages/yapsy/PluginManager.py", line 512, in loadPlugins
    plugin_info.plugin_object = self.instanciateElement(element)
  File "/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/plugin_manager.py", line 265, in instanciateElement
    return element(self.bot, name=self._current_pluginfo.name)

15:39:54 DEBUG    errbot.bootstrap          Start serving commands from the text backend
Some plugins failed to start during bot startup:
 File "/home/vagrant/.errbot-ve/lib/python3.4/site-packages/yapsy/PluginManager.py", line 512, in loadPlugins
    plugin_info.plugin_object = self.instanciateElement(element)
  File "/home/vagrant/.errbot-ve/lib/python3.4/site-packages/errbot/plugin_manager.py", line 265, in instanciateElement
    return element(self.bot, name=self._current_pluginfo.name)

 >>> 
```

**Comment by reikoNeko** [comment]
I had the same problem testing in centos 17.04 so there's something happening in the debian-family python package that doesn't in centos. The PluginManager comes from Errbot itself and I havenp;t spoken to the devs in some time.
Over the next couple weeks I'm returning to cleaning up the code and might make errbot 5.0.1 a requirement.

**Comment by viq** [comment]
If you want I could help you prepare a multi-node multi-system testing environment for this using Vagrant. And once you have some experience with that, you could integrate it with Travis CI here on github :) Or even start with that and skip the local multi-system setup, as they can do that for you, and are free for Open Source projects.

**Comment by reikoNeko** [comment]
That sounds tempting. Since I got it 95% working at my job this has become a side project and I'm looking for more contributors. My TODO list looks like:
* Create a permanent dev environment on my home machine with icinga2 running in a VM (done)
* Look at https://github.com/saurabh-hirani/icinga2_api as a potential replacement for my handmade api connector (doing)
* Add Unit Tests
* Make my bash-inflected python more object-oriented
* Add more interaction to the bot.

**Comment by viq** [comment]
Let me know whether you prefer to start with local vagrant or Travis and
I'll try to prepare something.

> --

viq

**Comment by cbinde** [comment]
Same problem here. Using centos 7, pip 9.01, python3.4 

I tried errbot 4.0.0, 4.1.0, 4.3.7 and 5.0.1..  It's not working. Which version of errbot did you used @reikoNeko ?

**Comment by reikoNeko** [comment]
Original development was in errbot 4.1.3. The following epel packages are on the host:
python3-rpm-macros.noarch              3-17.el7                        @epel    
python34.x86_64                        3.4.5-4.el7                     @epel    
python34-PyYAML.x86_64                 3.11-2.el7                      @epel    
python34-devel.x86_64                  3.4.5-4.el7                     @epel    
python34-libs.x86_64                   3.4.5-4.el7                     @epel    
python34-py.noarch                     1.4.30-2.el7                    @epel    
python34-setuptools.noarch             19.2-3.el7                      @epel    
python34-tkinter.x86_64                3.4.5-4.el7                     @epel    
python34-tools.x86_64                  3.4.5-4.el7                     @epel

The environment was created for the errbot user with `virtualenv -p python3.4 err`

**Comment by cbinde** [comment]
Still the same issue as viq reported. On centos 7 with exactly the same packages installed. 
Is there a chance to get that fixed?

**Comment by cbinde** [comment]
```
def __init__(self, bot):
 super().__init__(bot)
 self.stop_thread = threading.Event()
```
Needs to be changed to:
```
 def __init__(self, bot, name):
 super().__init__(bot, name)
 self.stop_thread = threading.Event()
```

**Comment by reikoNeko** [comment]
That doesn't work in the older version of Errbot, so please make a pull request. Looks like I'll need to write some wrapper code around this.

**Comment by reikoNeko** [comment]
Changed mind, No longer supporting Errbot 4, so this goes into main.

**Comment by viq** [comment]
After some debugging, it seems that the errors that me and other people are seeing are when trying to run the bot without the `CHATROOM_PRESENCE` set in the config (which default `errbot --init` doesn't set). I'll create a separate ticket for that.
