### ISSUE TITLE
Bot fails to start without `CHATROOM_PRESENCE` set, no useful logs generated

### ISSUE THREAD

**Issue by viq** [reikoNeko/icinga2bot#3]
After some debugging, it seems that the errors that me and other people are seeing are when trying to run the bot without the `CHATROOM_PRESENCE` set in the config (which default `errbot --init` doesn't set). The only indication of this is, after shuffling various thread functions around, following log:
```
2017-10-07 23:08:09,766 ERROR    errbot.plugin_manager     Error loading icinga2bot
Traceback (most recent call last):
  File "/home/viq/Work/Own/errbot/.errbot-venv/lib/python3.6/site-packages/errbot/plugin_manager.py", line 524, in activate_non_started_plugins
    self.activate_plugin_with_version_check(pluginInfo)
  File "/home/viq/Work/Own/errbot/.errbot-venv/lib/python3.6/site-packages/errbot/plugin_manager.py", line 310, in activate_plugin_with_version_check
    self.activatePluginByName(name, BOTPLUGIN_TAG)
  File "/home/viq/Work/Own/errbot/.errbot-venv/lib/python3.6/site-packages/yapsy/PluginManager.py", line 563, in activatePluginByName
    plugin_to_activate.activate()
  File "/home/viq/Work/Own/errbot/errbot-root/plugins/icinga2bot/icinga2bot.py", line 259, in activate
    self.room = self.query_room(self.bot_config.CHATROOM_PRESENCE[0])
IndexError: tuple index out of range

```

Please either handle such situation more gracefully, or at least produce a useful error message.

**Comment by reikoNeko** [comment]
Viq, Thanks. I'll wrap that in a try/except.

**Comment by reikoNeko** [comment]
Added homeroom() function to wrap the CHATROOM_PRESENCE check.

**Comment by viq** [comment]
Sorry, but with the minimal config that both come out of the box with it still fails. Steps (on debian 9, though that shouldn't matter):
```
virtualenv --python `which python3` ~/.errbot-ve
~/.errbot-ve/bin/pip install errbot
. ~/.errbot-ve/bin/activate
mkdir ~/errbot-root
cd ~/errbot-root
errbot --init
cd plugins/
git clone https://github.com/reikoNeko/icinga2bot
cd ..
errbot
[@CHANGE_ME ➡ @errbot] >>> !plugin activate icinga2bot
[@CHANGE_ME ➡ @errbot] [␍] 
Error activating plugin: icinga2bot failed to start : 'Icinga2bot' object has no attribute 'thread'
```

**Comment by reikoNeko** [comment]
What does the config.py file that errbot installed in your project directory look like? And which errbot version are you using?

**Comment by venuinu** [comment]
I am still seeing the attribute error similar to @viq .
Errbot version 5.1.3
Python 3.4
Ubuntu 14.04
